### ISSUE TITLE
website isn't working

### ISSUE THREAD

**Issue by AlexKnauth** [jarcane/try-racket#13]
If I go to try-racket.org or try.racket-lang.org, I get a Failed to open page can't connect to the server error.

**Comment by jarcane** [comment]
Fixed, server needed restarting. thanks for the heads up.

**Comment by a1ip** [comment]
Server is down again :(

**Comment by jarcane** [comment]
Should be back up in a moment.

The trouble is, it's only a wee little 512MB droplet, and for some reason
the server has been an open target almost from the moment it went online.

It's all firewalled and sandboxed so nothing gets through, but the constant
efforts of assholes bombarding the console with efforts to find escapes in
the REPL winds up crashing the Racket VM with an out of memory error
eventually. The effect is essentially an intermittent DOS attack.

At this point I'm considering soliciting volunteers who'd like to take up
the hosting duties, especially anyone with more experience securing
something like this properly.

**Comment by jarcane** [comment]
I've implemented a primitive shell script server-side now that should hopefully restart the server properly if and when it goes and crashes again.

**Comment by a1ip** [comment]
Great! Thank you @jarcane!
